# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=1.21.11
minecraft_version=1.21.11
loader_version=0.18.4
# Mod Properties
mod_version=2.5.1
maven_group=me.pigicial
archives_base_name=wikirenderer

# Dependencies
fabric_version=0.141.1+1.21.11

# https://maven.wispforest.io/io/wispforest/exo/
exo_version=0.1.5+1.19
# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib/
owo_version=0.13.0+1.21.11
iris_version=1.10.5+1.21.11-fabric
devauth_version=1.2.2
rei_version=21.11.814

litematica_version=1.21.11-0.26.0
malilib_version=1.21.11-0.27.6

# Gifski
gifski_version=1.34.0
gifski_hash=b9b6591aa163123d737353d9c8581efdf3234d28eeaa45329b31da905cd5a996